# This is a basic workflow to help you get started with Actions
name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch to run this workflow on"
        required: false
        default: "master"
        type: choice
        options:
          - main
          - dev
          - staging
          - feature

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Build Step
        run: |
          echo "Starting build..."
          echo "Simulating build for ${{ github.event.inputs.branch || github.ref_name }}"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Deploy Step
        run: |
          echo "Deploying application from ${{ github.event.inputs.branch || github.ref_name }}"
          # Add Terraform apply or AWS CLI logic here
